version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: "Update and install build tools"
          command: |
            sudo apt-get update
            sudo apt-get install build-essential cmake clang libc6-dev-i386


