version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: "Test env vars"
          command: |
            export CATS="dogs"
            echo $CATS

